//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McMapViewerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chunk
    {
        public Chunk()
        {
            this.Geometries = new HashSet<Geometry>();
        }
    
        public int ID { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int MapRevisionID { get; set; }
    
        public virtual MapRevision MapRevision { get; set; }
        public virtual ICollection<Geometry> Geometries { get; set; }
    }
}
