//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McMapViewerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceVertexUV
    {
        public FaceVertexUV()
        {
            this.UVs = new HashSet<UV>();
            this.UVs1 = new HashSet<UV>();
            this.UVs2 = new HashSet<UV>();
        }
    
        public int ID { get; set; }
        public int FaceID { get; set; }
        public int UvA { get; set; }
        public int UvB { get; set; }
        public int UvC { get; set; }
    
        public virtual Face Face { get; set; }
        public virtual ICollection<UV> UVs { get; set; }
        public virtual ICollection<UV> UVs1 { get; set; }
        public virtual ICollection<UV> UVs2 { get; set; }
    }
}
