//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McMapViewerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Face
    {
        public Face()
        {
            this.FaceVertexUVs = new HashSet<FaceVertexUV>();
            this.Verts = new HashSet<Vert>();
            this.Verts1 = new HashSet<Vert>();
            this.Verts2 = new HashSet<Vert>();
        }
    
        public int ID { get; set; }
        public int VertA { get; set; }
        public int VertB { get; set; }
        public int VertC { get; set; }
        public int GeometryID { get; set; }
    
        public virtual Geometry Geometry { get; set; }
        public virtual ICollection<FaceVertexUV> FaceVertexUVs { get; set; }
        public virtual ICollection<Vert> Verts { get; set; }
        public virtual ICollection<Vert> Verts1 { get; set; }
        public virtual ICollection<Vert> Verts2 { get; set; }
    }
}
