//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McMapViewerDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class McMapViewerEntities : DbContext
    {
        public McMapViewerEntities()
            : base("name=McMapViewerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chunk> Chunks { get; set; }
        public virtual DbSet<Face> Faces { get; set; }
        public virtual DbSet<FaceVertexUV> FaceVertexUVs { get; set; }
        public virtual DbSet<Geometry> Geometries { get; set; }
        public virtual DbSet<MapRevision> MapRevisions { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<UV> UVs { get; set; }
        public virtual DbSet<Vert> Verts { get; set; }
    }
}
