//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McMapViewerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vert
    {
        public int MapRevisionID { get; set; }
        public int OrderID { get; set; }
        public float X { get; set; }
        public float Y { get; set; }
        public float Z { get; set; }
    
        public virtual Face Face { get; set; }
        public virtual Face Face1 { get; set; }
        public virtual Face Face2 { get; set; }
    }
}
